DROP DATABASE IF EXISTS blogv1;
CREATE DATABASE IF NOT EXISTS blogV1;
USE blogV1;

DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users(
	id		int AUTO_INCREMENT PRIMARY KEY,
    username	VARCHAR(50) NOT NULL UNIQUE,
    `password`	VARCHAR(100) NOT NULL ,
    email		VARCHAR(100) NOT NULL UNIQUE,
    full_name	VARCHAR(100),
    created_at	DATETIME DEFAULT CURRENT_TIMESTAMP,
    updates_at	DATETIME DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS Categories;
CREATE TABLE IF NOT EXISTS Categories(
	id			INT PRIMARY KEY AUTO_INCREMENT,
    `name`		VARCHAR(50) NOT NULL,
    created_at	DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at	DATETIME DEFAULT CURRENT_TIMESTAMP
);
DROP TABLE IF EXISTS Posts;
CREATE TABLE IF NOT EXISTS Posts(
	id 			INT AUTO_INCREMENT PRIMARY KEY,
    title		VARCHAR(255) NOT NULL,
    content		TEXT,
    author_id 	INT,
    category_id	INT,
    created_at	DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at	DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (author_id) REFERENCES Users(id),
    FOREIGN KEY	(category_id) REFERENCES Categories(id)
);
DROP TABLE IF EXISTS Comments;
CREATE TABLE IF NOT EXISTS Comments(
	id			INT PRIMARY KEY AUTO_INCREMENT,
    post_id		INT,
    content		TEXT,
    author_id	INT,
    created_at	DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at	DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES Posts(id),
    FOREIGN KEY (author_id) REFERENCES Users(id)
);
DROP TABLE IF EXISTS Tags;
CREATE TABLE IF NOT EXISTS Tags(
	id 			INT PRIMARY KEY AUTO_INCREMENT,
    `name`		VARCHAR(50) NOT NULL,
	created_at 	DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at	DATETIME DEFAULT CURRENT_TIMESTAMP
);


